"""empty message

Revision ID: 541df22f727e
Revises: 529ecc968e56
Create Date: 2021-08-27 17:48:39.959256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541df22f727e'
down_revision = '529ecc968e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
