"""empty message

Revision ID: 7dc9cd2e0a39
Revises: 541df22f727e
Create Date: 2021-08-27 17:52:47.310423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc9cd2e0a39'
down_revision = '541df22f727e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('images', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('images', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
