"""empty message

Revision ID: b88b8e2cdcf6
Revises: 7dc9cd2e0a39
Create Date: 2021-08-30 21:23:23.099025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88b8e2cdcf6'
down_revision = '7dc9cd2e0a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('zipcode', sa.String(length=50), nullable=False))
    op.alter_column('images', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('applications', 'zipcode')
    op.drop_column('applications', 'state')
    op.drop_column('applications', 'city')
    # ### end Alembic commands ###
