"""empty message

Revision ID: 529ecc968e56
Revises: 9a5fd58cc6ab
Create Date: 2021-08-24 17:54:08.642995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529ecc968e56'
down_revision = '9a5fd58cc6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('applications', sa.Column('cellphone', sa.String(length=50), nullable=False))
    op.add_column('applications', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'address')
    op.drop_column('applications', 'cellphone')
    op.drop_column('applications', 'email')
    op.drop_column('applications', 'age')
    op.drop_column('applications', 'name')
    # ### end Alembic commands ###
